name: deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
       matrix:
         platform: [linux/amd64, linux/arm64]
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        uses: |
          docker build -t python-helloworld .
          docker tag python-helloworld python-helloworld:latest
          docker push mwess89/python-helloworld:latest
